import Head from 'next/head'
import {useState} from "react";
import {CircularProgress} from "@chakra-ui/react";
import {wrapper} from "@/styles/Home.module.css";


export default function Home() {
    const [isLoading] = useState(false);
    return (
        <>
            <Head>
                <title>Chat App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={`${wrapper}`}>
                {isLoading && <CircularProgress value={30} color='orange' thickness='12px' isIndeterminate={true}/>}
            </main>
        </>
    )
}
