import Head from 'next/head'
import {Inter} from 'next/font/google'
import styles from '@/styles/Home.module.css'
import {FormEvent, useState} from "react";
import {Box} from "@chakra-ui/react";
import {AUTH_INFOS} from "@/constant/storage";

const inter = Inter({subsets: ['latin']})

type AuthInfos = {
    username: string;
    password: string;
}


export default function Home() {
    const [authInfos, setAuthInfos] = useState<AuthInfos>(null);

    function handleSubmit(e: FormEvent) {
        e.preventDefault();
        localStorage.setItem(AUTH_INFOS, JSON.stringify(authInfos));
    }

    function handleInputChange<T>(originalFlatObj: T, attribute: keyof T){
        return (event) => setAuthInfos({
            ...originalFlatObj,
            [attribute]: event.target.value
        });
    }

    return (
        <>
            <Head>
                <title>Chat App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={`${styles.main} ${inter.className}`}>
                <form className={styles.wrapper}>
                    <label>
                        <input type={"text"} name={"username"}
                               className={`${styles.wrapper__input}`}
                               onChange={handleInputChange<AuthInfos>(authInfos, "username")}
                                placeholder={"Username or Email"}
                        />
                    </label>
                    <label>
                        <input type={"password"} name={"password"}
                               className={`${styles.wrapper__input}`}
                               onChange={handleInputChange(authInfos, "password")}
                            placeholder={"Password"}
                        />
                    </label>
                    <input type={"submit"} value={"Log In"} className={styles.submit} onClick={handleSubmit}/>
                </form>
            </main>
        </>
    )
}
