import React, {useState} from 'react';
import Head from "next/head";
import {useAuthStore} from "@/store/auth-store";
import {Box, Button, Grid, GridItem, HStack, Image, Text} from "@chakra-ui/react";
import {LockIcon, EditIcon} from "@chakra-ui/icons";
import EditableWithControl from "@/components/common/EditableWithControl";
import useStore from "@/store/use-store";

function Profile() {
    const user = useStore(useAuthStore, (state)=> state.user);

    return (
        <div>
            <Head>
                <title>Profile</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main>
                <Box margin='auto' pb={'5'} w={'fit-content'} borderBottom={'1px solid'}>
                    <Image src='/assets/icon/user-avatar.png' alt='Profile image'/>
                    <Text as={'b'} display={'block'}>@{user?.name}</Text>
                    <Text as={'cite'}>{user?.bio || "Your bio"}</Text>
                </Box>
                <Grid mt={'10'} templateAreas={`"aside main backSide"`} gridAutoColumns={'20% 1fr 20%'}>
                    <GridItem area={'main'}>
                        <Box>
                            <Text as={"b"}>Email</Text>
                            <EditableWithControl defaultValue={user?.email||''}
                                                 onSubmit={(value: string) => {
                                                     // todo implement me
                                                 }}
                            />
                        </Box>
                        <HStack flex={1} justifyContent={'end'} mt={'10'}>
                            <Button colorScheme='yellow' rightIcon={<EditIcon/>}>Edit Profile</Button>
                            <Button colorScheme='red' rightIcon={<LockIcon/>}>Logout</Button>
                        </HStack>
                    </GridItem>
                </Grid>
            </main>
        </div>
    );
}

export default Profile;